// Comprehensive market data - Popular stocks and ETFs

export const POPULAR_STOCKS = [
  // Technology
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology", marketCap: "2.85T" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology", marketCap: "2.79T" },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Technology", marketCap: "1.68T" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Technology", marketCap: "1.56T" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology", marketCap: "1.22T" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Technology", marketCap: "892B" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Technology", marketCap: "758B" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology", marketCap: "682B" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology", marketCap: "328B" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology", marketCap: "267B" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology", marketCap: "259B" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology", marketCap: "234B" },
  { symbol: "INTC", name: "Intel Corporation", sector: "Technology", marketCap: "193B" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology", marketCap: "214B" },

  // Healthcare
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare", marketCap: "512B" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", marketCap: "385B" },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare", marketCap: "738B" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", marketCap: "312B" },
  { symbol: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare", marketCap: "257B" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare", marketCap: "162B" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", marketCap: "212B" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare", marketCap: "195B" },

  // Financials
  { symbol: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", marketCap: "878B" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials", marketCap: "584B" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials", marketCap: "562B" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financials", marketCap: "429B" },
  { symbol: "BAC", name: "Bank of America Corp.", sector: "Financials", marketCap: "318B" },
  { symbol: "WFC", name: "Wells Fargo & Company", sector: "Financials", marketCap: "212B" },
  { symbol: "GS", name: "Goldman Sachs Group", sector: "Financials", marketCap: "158B" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials", marketCap: "172B" },

  // Consumer Discretionary
  { symbol: "COST", name: "Costco Wholesale", sector: "Consumer Discretionary", marketCap: "368B" },
  { symbol: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary", marketCap: "392B" },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary", marketCap: "214B" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary", marketCap: "128B" },
  { symbol: "SBUX", name: "Starbucks Corporation", sector: "Consumer Discretionary", marketCap: "112B" },

  // Energy
  { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy", marketCap: "442B" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy", marketCap: "286B" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", marketCap: "142B" },
  { symbol: "SLB", name: "Schlumberger Limited", sector: "Energy", marketCap: "63B" },

  // Industrials
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials", marketCap: "118B" },
  { symbol: "BA", name: "Boeing Company", sector: "Industrials", marketCap: "124B" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials", marketCap: "178B" },
  { symbol: "GE", name: "General Electric", sector: "Industrials", marketCap: "192B" },

  // Communications
  { symbol: "DIS", name: "Walt Disney Company", sector: "Communications", marketCap: "168B" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communications", marketCap: "287B" },
  { symbol: "CMCSA", name: "Comcast Corporation", sector: "Communications", marketCap: "172B" },
];

export const POPULAR_ETFS = [
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    category: "Large Cap",
    description: "Tracks the S&P 500 index. The largest and most traded ETF in the world.",
    holdings: "500+ stocks",
    expenseRatio: "0.09%",
    aum: "$442B",
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    category: "Technology",
    description: "Tracks the Nasdaq-100 index. Heavy concentration in technology stocks.",
    holdings: "100 stocks",
    expenseRatio: "0.20%",
    aum: "$237B",
  },
  {
    symbol: "VOO",
    name: "Vanguard S&P 500 ETF",
    category: "Large Cap",
    description: "Low-cost alternative to SPY, also tracks the S&P 500 index.",
    holdings: "500+ stocks",
    expenseRatio: "0.03%",
    aum: "$421B",
  },
  {
    symbol: "VTI",
    name: "Vanguard Total Stock Market ETF",
    category: "Total Market",
    description: "Broadest U.S. equity exposure, covers entire stock market including small-cap.",
    holdings: "3,800+ stocks",
    expenseRatio: "0.03%",
    aum: "$378B",
  },
  {
    symbol: "IWM",
    name: "iShares Russell 2000 ETF",
    category: "Small Cap",
    description: "Tracks the Russell 2000 index of small-cap U.S. stocks.",
    holdings: "2,000 stocks",
    expenseRatio: "0.19%",
    aum: "$63B",
  },
  {
    symbol: "DIA",
    name: "SPDR Dow Jones Industrial Average ETF",
    category: "Large Cap",
    description: "Tracks the 30 stocks in the Dow Jones Industrial Average.",
    holdings: "30 stocks",
    expenseRatio: "0.16%",
    aum: "$31B",
  },
  {
    symbol: "AGG",
    name: "iShares Core U.S. Aggregate Bond ETF",
    category: "Bonds",
    description: "Broad exposure to U.S. investment-grade bonds.",
    holdings: "10,000+ bonds",
    expenseRatio: "0.03%",
    aum: "$98B",
  },
  {
    symbol: "GLD",
    name: "SPDR Gold Shares",
    category: "Commodities",
    description: "Tracks the price of gold bullion. Popular hedge against inflation.",
    holdings: "Gold bullion",
    expenseRatio: "0.40%",
    aum: "$58B",
  },
  {
    symbol: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    category: "Bonds",
    description: "Invests in long-term U.S. Treasury bonds.",
    holdings: "30+ bonds",
    expenseRatio: "0.15%",
    aum: "$47B",
  },
  {
    symbol: "VNQ",
    name: "Vanguard Real Estate ETF",
    category: "Real Estate",
    description: "Provides exposure to U.S. real estate investment trusts (REITs).",
    holdings: "160+ REITs",
    expenseRatio: "0.12%",
    aum: "$38B",
  },
  {
    symbol: "XLK",
    name: "Technology Select Sector SPDR",
    category: "Technology",
    description: "Invests in technology companies from the S&P 500.",
    holdings: "65+ stocks",
    expenseRatio: "0.10%",
    aum: "$56B",
  },
  {
    symbol: "XLF",
    name: "Financial Select Sector SPDR",
    category: "Financials",
    description: "Focuses on financial sector stocks from the S&P 500.",
    holdings: "70+ stocks",
    expenseRatio: "0.10%",
    aum: "$42B",
  },
  {
    symbol: "XLE",
    name: "Energy Select Sector SPDR",
    category: "Energy",
    description: "Invests in energy sector stocks from the S&P 500.",
    holdings: "23 stocks",
    expenseRatio: "0.10%",
    aum: "$35B",
  },
  {
    symbol: "XLV",
    name: "Health Care Select Sector SPDR",
    category: "Healthcare",
    description: "Provides exposure to healthcare companies from the S&P 500.",
    holdings: "65+ stocks",
    expenseRatio: "0.10%",
    aum: "$38B",
  },
  {
    symbol: "ARKK",
    name: "ARK Innovation ETF",
    category: "Innovation",
    description: "Actively managed fund focusing on disruptive innovation.",
    holdings: "35-55 stocks",
    expenseRatio: "0.75%",
    aum: "$8B",
  },
  {
    symbol: "VGT",
    name: "Vanguard Information Technology ETF",
    category: "Technology",
    description: "Low-cost technology sector ETF with broad exposure.",
    holdings: "320+ stocks",
    expenseRatio: "0.10%",
    aum: "$64B",
  },
  {
    symbol: "EEM",
    name: "iShares MSCI Emerging Markets ETF",
    category: "Emerging Markets",
    description: "Exposure to emerging market equities.",
    holdings: "1,400+ stocks",
    expenseRatio: "0.68%",
    aum: "$26B",
  },
  {
    symbol: "VEA",
    name: "Vanguard FTSE Developed Markets ETF",
    category: "International",
    description: "Invests in developed international markets excluding the U.S.",
    holdings: "4,000+ stocks",
    expenseRatio: "0.05%",
    aum: "$118B",
  },
];

export const SECTORS = {
  Technology: POPULAR_STOCKS.filter((s) => s.sector === "Technology"),
  Healthcare: POPULAR_STOCKS.filter((s) => s.sector === "Healthcare"),
  Financials: POPULAR_STOCKS.filter((s) => s.sector === "Financials"),
  "Consumer Discretionary": POPULAR_STOCKS.filter(
    (s) => s.sector === "Consumer Discretionary"
  ),
  Energy: POPULAR_STOCKS.filter((s) => s.sector === "Energy"),
  Industrials: POPULAR_STOCKS.filter((s) => s.sector === "Industrials"),
  Communications: POPULAR_STOCKS.filter((s) => s.sector === "Communications"),
};
